project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - reading_list.qmd
  - lab_1.qmd
  #- tutorial/tutorial_1.qmd
  #- tutorial/tutorial_2.qmd
  - notes/notes_1.qmd
  - notes/notes_2.qmd
  - notes/notes_3.qmd
  - supplementary/supl_1.qmd
  - slides/slides_1.qmd
  - slides/slides_2.qmd
  - slides/slides_3.qmd
website:
  title: "Module 1"
  page-footer:
    center: '<a href="https://envstats-stats4009-stats503.github.io/Course_Notes/2025_26/Module_1/docs/" style="color:#ccc;">Home</a>'
  navbar:
    logo: UofG.png
    right:
      - text: "Home"
        href: index.qmd
    left:
      - text: "Notes"
        menu:
          - text: "Week 1"
            href:  notes/notes_1.qmd
          - text: "Week 2"
            href:  notes/notes_2.qmd
          - text: "Week 3"
            href:  notes/notes_3.qmd
      - text: "Slides"
        menu:
          - text: "Week 1 - Introduction"
            href: slides/slides_1.qmd
          - text: "Week 2 - Understanding our Data"
            href: slides/slides_2.qmd
          - text: "Week 3 - Sampling & Monitoring"
            href: slides/slides_3.qmd
      - text: "Supplementary Notes"
        menu:
          - text: "Properties of estimators"
            href:  supplementary/supl_1.qmd
      - text: "Tutorials"
        menu:
          - text: "Practical 1 - inlabru workflow"
            href: notes/notes_1.qmd
          - text: "Practical 2 - spatial modelling"
            href: notes/notes_1.qmd
      - text: "Lab"
        menu:
          - text: "Lab 1"
            href: lab_1.qmd
      - text: "Reading List"
        href: reading_list.qmd
format:
  html:
    mainfont: serif
    theme:
      light: flatly
      dark: darkly
    css:
      - styles.css
      - include/webex.css
    toc: true
    include-after-body: include/webex.js
editor: visual
