project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - reading_list.qmd
  - lab_2.qmd
  - notes/tutorial_sheet_2.qmd
  - notes/tutorial_sheet_3.qmd
  - notes/tutorial_sheet_2_solutions.qmd
  - notes/tutorial_sheet_3_solutions.qmd
  - notes/notes_1.qmd
  - notes/notes_2.qmd
  - notes/notes_3.qmd
  - slides/slides_6.qmd
website:
  title: "Module 2"
  page-footer:
    center: '<a href="https://envstats-stats4009-stats503.github.io/Course_Notes/2025_26/Module_2/docs/" style="color:#ccc;">Home</a>'
  navbar:
    logo: UofG.png
    right:
      - text: "Home"
        href: index.qmd
    left:
      - text: "Notes"
        menu:
          - text: "Week 4 - Assessing Change Over Time"
            href:  notes/notes_1.qmd
          - text: "Week 5 - Autocorrelation & Changepoints"
            href:  notes/notes_2.qmd
          - text: "Week 6- Modelling Extremes"
            href:  notes/notes_3.qmd
      - text: "Slides"
        menu:
          - text: "Week 4 - Assessing Change Over Time"
            href: slides/Week_4.pdf
          - text: "Week 5 - Autocorrelation & Changepoints"
            href: slides/Week_5.pdf
          - text: "Week 6 - Modelling Extremes"
            href: slides/slides_6.qmd
      - text: "Tutorials"
        menu:
          - text: "Tutorial sheet 2"
            href: notes/tutorial_sheet_2.qmd
          - text: "Tutorial sheet 3"
            href: notes/tutorial_sheet_3.qmd
      - text: "Labs"
        menu:
          - text: "Lab 2"
            href: lab_2.qmd
      - text: "Reading List"
        href: reading_list.qmd
format:
  html:
    embed-resources: false
    mainfont: serif
    theme:
      light: flatly
      dark: darkly
    css:
      - styles.css
      - include/webex.css
    toc: true
    include-after-body: include/webex.js
editor: visual
filters:
  - shinylive
